module.exports = {
  country: 'Colombia',
  departments: [
    { name: 'Amazonas', cities: ['Leticia', 'Puerto Nariño', 'N/A'] },
    { name: 'Antioquia', cities: ['Medellín', 'Bello', 'Itagüí', 'Envigado', 'Sabaneta', 'La Estrella', 'Caldas', 'Copacabana', 'Girardota', 'Barbosa', 'Rionegro', 'Apartadó', 'Turbo', 'Caucasia', 'Puerto Berrío', 'N/A'] },
    { name: 'Arauca', cities: ['Arauca', 'Arauquita', 'Fortul', 'Puerto Rondón', 'Saravena', 'Tame', 'Cravo Norte', 'N/A'] },
    { name: 'Atlántico', cities: ['Barranquilla', 'Soledad', 'Malambo', 'Sabanalarga', 'Santo Tomás', 'Baranoa', 'Galapa', 'Puerto Colombia', 'N/A'] },
    { name: 'Bogotá D.C.', cities: ['Bogotá'] },
    { name: 'Bolívar', cities: ['Cartagena', 'Magangué', 'El Carmen de Bolívar', 'Mompox', 'Turbaco', 'Arjona', 'N/A'] },
    { name: 'Boyacá', cities: ['Tunja', 'Duitama', 'Sogamoso', 'Chiquinquirá', 'Paipa', 'Moniquirá', 'Garagoa', 'Guateque', 'N/A'] },
    { name: 'Caldas', cities: ['Manizales', 'Villamaría', 'Chinchiná', 'Riosucio', 'La Dorada', 'Manzanares', 'Anserma', 'N/A'] },
    { name: 'Caquetá', cities: ['Florencia', 'San Vicente del Caguán', 'Puerto Rico', 'Belén de los Andaquíes', 'La Montañita', 'N/A'] },
    { name: 'Casanare', cities: ['Yopal', 'Aguazul', 'Villanueva', 'Tauramena', 'Paz de Ariporo', 'Trinidad', 'N/A'] },
    { name: 'Cauca', cities: ['Popayán', 'Santander de Quilichao', 'Puerto Tejada', 'El Tambo', 'Patía', 'N/A'] },
    { name: 'Cesar', cities: ['Valledupar', 'Aguachica', 'Codazzi', 'La Jagua de Ibirico', 'Chiriguaná', 'Bosconia', 'N/A'] },
    { name: 'Chocó', cities: ['Quibdó', 'Istmina', 'Condoto', 'Unguía', 'Nuquí', 'Bahía Solano', 'N/A'] },
    { name: 'Córdoba', cities: ['Montería', 'Tierralta', 'Cereté', 'Lorica', 'Sahagún', 'Montelíbano', 'Ciénaga de Oro', 'N/A'] },
    { name: 'Cundinamarca', cities: ['Soacha', 'Facatativá', 'Zipaquirá', 'Girardot', 'Fusagasugá', 'Chía', 'Cajicá', 'Mosquera', 'Madrid', 'Funza', 'Tocancipá', 'La Mesa', 'Villeta', 'N/A'] },
    { name: 'Guainía', cities: ['Inírida', 'Barranco Minas', 'Mapiripana', 'N/A'] },
    { name: 'Guaviare', cities: ['San José del Guaviare', 'Calamar', 'El Retorno', 'Miraflores', 'N/A'] },
    { name: 'Huila', cities: ['Neiva', 'Pitalito', 'Garzón', 'La Plata', 'Campoalegre', 'Palermo', 'Santana', 'N/A'] },
    { name: 'La Guajira', cities: ['Riohacha', 'Maicao', 'Villanueva', 'San Juan del Cesar', 'Manaure', 'Uribia', 'Albania', 'N/A'] },
    { name: 'Magdalena', cities: ['Santa Marta', 'Ciénaga', 'Fundación', 'El Banco', 'Plato', 'Aracataca', 'N/A'] },
    { name: 'Meta', cities: ['Villavicencio', 'Acacías', 'Granada', 'Puerto López', 'Puerto Gaitán', 'La Macarena', 'Cumaral', 'N/A'] },
    { name: 'Nariño', cities: ['Pasto', 'Ipiales', 'Tumaco', 'La Unión', 'Túquerres', 'Samaniego', 'Sandoná', 'N/A'] },
    { name: 'Norte de Santander', cities: ['Cúcuta', 'Ocaña', 'Pamplona', 'Villa del Rosario', 'Los Patios', 'Tibú', 'N/A'] },
    { name: 'Putumayo', cities: ['Mocoa', 'Puerto Asís', 'Valle del Guamuez', 'Orito', 'Villagarzón', 'Sibundoy', 'N/A'] },
    { name: 'Quindío', cities: ['Armenia', 'Calarcá', 'Montenegro', 'Quimbaya', 'La Tebaida', 'Circasia', 'Salento', 'N/A'] },
    { name: 'Risaralda', cities: ['Pereira', 'Dosquebradas', 'Santa Rosa de Cabal', 'La Virginia', 'Marsella', 'Santuario', 'N/A'] },
    { name: 'San Andrés y Providencia', cities: ['San Andrés', 'Providencia', 'N/A'] },
    { name: 'Santander', cities: ['Bucaramanga', 'Floridablanca', 'Girón', 'Piedecuesta', 'Barrancabermeja', 'Málaga', 'San Gil', 'Socorro', 'Vélez', 'N/A'] },
    { name: 'Sucre', cities: ['Sincelejo', 'Corozal', 'San Marcos', 'Sampués', 'Tolú', 'N/A'] },
    { name: 'Tolima', cities: ['Ibagué', 'Espinal', 'Melgar', 'Líbano', 'Honda', 'Chaparral', 'Flandes', 'N/A'] },
    { name: 'Valle del Cauca', cities: ['Cali', 'Buenaventura', 'Palmira', 'Tuluá', 'Cartago', 'Buga', 'Jamundí', 'Florida', 'Yumbo', 'Candelaria', 'N/A'] },
    { name: 'Vaupés', cities: ['Mitú', 'Taraira', 'Carurú', 'Yavaraté', 'N/A'] },
    { name: 'Vichada', cities: ['Puerto Carreño', 'La Primavera', 'Santa Rosalía', 'Cumaribo', 'N/A'] },
  ],
  bogotaAreas: [
    'Antonio Nariño',
    'Barrios Unidos',
    'Bosa',
    'Chapinero',
    'Ciudad Bolívar',
    'Engativá',
    'Fontibón',
    'Kennedy',
    'La Candelaria',
    'Los Mártires',
    'Puente Aranda',
    'Rafael Uribe Uribe',
    'San Cristóbal',
    'Santa Fe',
    'Suba',
    'Sumapaz',
    'Teusaquillo',
    'Tunjuelito',
    'Usaquén',
    'Usme',
    'N/A',
  ]
};
